### ISSUE TITLE
Image fails to launch?

### ISSUE THREAD

**Issue by cboettig** [binder-examples/r#10]
Not sure what I'm doing wrong, could be a chance error.  Image seemed to have built (after some time) and pushed successfully, but fails to launch server: 

https://mybinder.org/v2/gh/cboettig/geocompr/master?urlpath=rstudio

error message in the log isn't particularly informative:

```
Image gcr.io/binder-prod/r2d-05168b0-cboettig-2dgeocompr-38e476:d1bd8016f74bb9b56e982fe9eca7a08a5d9f2a5c for user cboettig-geocompr-r5xgth94 failed to launch
```

Any ideas?

**Comment by choldgraf** [comment]
Ah - I see you have a Dockerfile in there as well. If Binder finds a Dockerfile, it'll default to using this instead of any other "config" files in there. Your Dockerfile doesn't [adhere to the Binder dockerfile spec](https://mybinder.readthedocs.io/en/latest/dockerfile.html) so I think that's why the image isn't launching properly.

To avoid this, you could put your `install.R` and `runtime.txt` into a folder called `binder/`, and then Binder will use those configuration files instead of whatever is in the root of the repo. Does that work?

**Comment by cboettig** [comment]
Thanks! I didn't know you could use a `binder/` subdir, that's perfect.  (This is a fork of another user's repo who had provided a Dockerfile already, I wanted to show in PR that they could go a step farther by also providing the binder link!)

**Comment by choldgraf** [comment]
woot!
