### ISSUE TITLE
MRAN - package ‘devtools’ is not available

### ISSUE THREAD

**Issue by franzbischoff** [binder-examples/r#30]
Hello,

New compilation for R repositories based on MRAN are giving this error (including mybinder example https://mybinder.org/v2/gh/binder-examples/binder-r-description/master?urlpath=rstudio)

I'm using runtime.txt with the following string: r-3.6-2020-04-20, and I changed to r-3.6-2020-07-22 (last devtools snapshot on MRAN is 07-21) and the error persists.

```
> install.packages('devtools', repos='https://mran.microsoft.com/snapshot/2018-02-01', method='libcurl')
Installing package into ‘/srv/rlibs’
(as ‘lib’ is unspecified)
Warning: unable to access index for repository https://mran.microsoft.com/snapshot/2018-02-01/src/contrib:
  Line starting '<!doctype html><html ...' is malformed!
Warning message:
package ‘devtools’ is not available (for R version 3.6.3)
```

**Comment by cboettig** [comment]
Looks like a problem redirects, though haven't checked if that's due to Microsoft not creating them properly or R not following them.  Microsoft appears to have moved it base URL for MRAN to <https://cran.microsoft.com> instead of `mran.microsoft...`.  Try setting `repos="https://cran.microsoft.com/snapshot/2018-02-01"` instead.

**Comment by franzbischoff** [comment]
You mean in settings.txt?

```
r-3.6-2020-04-20
repos="https://cran.microsoft.com/snapshot/2018-02-01"
```
